services:
  redis:
    image: redis:7.4.2
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Montar la configuración personalizada
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  redis-data: